pleural thickening: "Increased thickness of the pleura seen as a dense layer around the lung."
atelectasis: "Collapsed lung tissue causing darkened or shrunken areas in the lung."
pleural effusion: "Excess fluid in the pleural space appearing as a shadow around the lungs."
cardiomegaly: "Enlargement of the heart seen when the heart appears larger than normal."
aortic elongation: "Lengthened and tortuous aorta, visible as an elongated curving structure."
vertebral degenerative changes: "Irregular vertebral margins with bony sclerosis and osteophytes."
aortic atheromatosis: "Calcified deposits in the aortic wall appearing as bright, irregular opacities."
nodule: "A growth or lump in the lung which may appear as a well-defined or irregular shape."
alveolar pattern: "Cloud-like, patchy opacities representing fluid or cellular accumulation in alveoli."
hiatal hernia: "A soft-tissue mass or air-fluid level above the diaphragm, near the midline."
scoliosis: "Sideways curvature of the spine causing  misalignment of vertebral bodies."
hemidiaphragm elevation: "One side of the diaphragm appearing higher than the other, with convex shape."
hyperinflated lung: "Abnormally increased lung volume with expanded air spaces."
interstitial pattern: "Fine reticular or nodular opacities spread across the lung, indicating interstitial involvement."
fracture: "A break in the bone appearing as a radiolucent line or displacement."
vascular hilar enlargement: "Increased prominence of the pulmonary vessels near the lung hila."
nsg tube: "A thin radiopaque tube extending from the nasal cavity into the stomach."
endotracheal tube: "A thin or opaque line in the middle of the trachea.  "
hypoexpansion: "Reduced lung inflation with increased density and narrow intercostal spaces."
central venous catheter: "A visible line inside large vein."
electrical device: "A dense, well-defined metallic opacity, typically a pacemaker or defibrillator."
bronchiectasis: "Dilated bronchi with thick walls, appearing as tubular or cystic opacities."
goiter: "A soft tissue mass in the anterior neck, sometimes displacing the trachea."
other entities: "An unusual mass or area in the lung with irregular borders or density." 