lung opacity: "An area of increased density in the lung fields typically appearing as a white or grayish patch."
infiltration: "Accumulation of substances or cells in the lung tissue visible as increased density or nodules."
consolidation: "Lung tissue filled with fluid or cells causing dense solid areas on imaging."
nodule or mass: "A growth or lump in the lung which may appear as a well-defined or irregular shape."
pleural thickening: "Increased thickness of the pleura seen as a dense layer around the lung."
aortic enlargement: "Widening of the aorta visible as an enlarged artery on imaging."
pulmonary fibrosis: "Scarring of the lung tissue creating a dense fibrous appearance."
ild: "Scarring or inflammation of the lung’s interstitial tissue creating a reticular or nodular pattern."
cardiomegaly: "Enlargement of the heart seen when the heart appears larger than normal."
other lesion: "An unusual mass or area in the lung with irregular borders or density."
pleural effusion: "Excess fluid in the pleural space appearing as a shadow around the lungs."
calcification: "Calcium deposits in lung tissue visible as bright white spots."
enlarged pa: "Widening of the pulmonary artery seen as an enlarged artery in the chest."
lung cavity: "Air-filled spaces within the lung often surrounded by dense tissue."
atelectasis: "Collapsed lung tissue causing darkened or shrunken areas in the lung."
mediastinal shift: "Displacement of central chest structures like the heart to one side."
lung cyst: "Fluid-filled spaces in the lung often round with thin walls."
pneumothorax: "Air trapped in the pleural space creating a gap or absence of lung tissue."
emphysema: "Enlarged air spaces in the lungs appearing over-expanded or damaged."
clavicle fracture: "A break in the collarbone seen as a gap or irregularity in the bone."
rib fracture: "A break in one or more ribs appearing as a visible crack or displacement."
edema: "Fluid accumulation in the lungs creating a hazy or clouded area."
